ALTER TABLE purchase_orders
  ADD COLUMN IF NOT EXISTS freight NUMERIC(20, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS surcharge NUMERIC(20, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fumigation NUMERIC(20, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS document_charges NUMERIC(20, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount NUMERIC(20, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS other_charges NUMERIC(20, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS charges_edited BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'Open',
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();
